### ISSUE TITLE
unsubscribe the event handler on unmount

### ISSUE THREAD

**Issue by capaj** [pagarme/react-event-components#1]
I haven't tried it, but just looking at the code https://github.com/pagarme/react-event-components/blob/master/src/react-event-components/KeyUp.js it seems there's no unsubscribe.

That is a basic thing, I as a react developer would expect to be handled by this library.

**Comment by MarcoWorms** [comment]
I'll do that. Thanks!

**Comment by derekstavis** [comment]
Thanks @capaj for the report!

**Comment by MarcoWorms** [comment]
done :)

https://github.com/pagarme/react-event-components/commit/daefce62bc488179621dc94a3b5a5ee0e03d8f00

**Comment by derekstavis** [comment]
Pushed to NPM as version 0.1.3 :+1:
