### ISSUE TITLE
Cannot use this package from npm with create-react-app

### ISSUE THREAD

**Issue by felquis** [pagarme/react-event-components#30]
To simulate, run these commands:

1. `create-react-app test`
1. `cd test`
1. `npm install react-event-components`
1. Go to App.js
1. write `import { Every } from 'react-event-components'`

Then try to run the project,

It happens with version 0.1.6
I tested it with yarn, but I think it happens too with npm.

👐

**Comment by derekstavis** [comment]
Working on this!

**Comment by derekstavis** [comment]
Could you please try if the branch `can-i-haz-build` works for you?

Just replace `react-event-components` on `npm install` by `https://github.com/pagarme/react-event-components#can-i-haz-build` and you can test this branch.

Please repeat the steps and give feedback! Thanks!

**Comment by myappincome** [comment]
I had an issue with create-react-app too. Probably the same, but I was getting:

Error in ./~/react-event-components/src/react-event-components/KeyUp.js
Module parse failed: C:\Work\MeetingCost\node_modules\react-event-components\src\react-event-components\KeyUp.js Unexpected token (5:25)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (5:25)
 @ ./~/react-event-components/src/react-event-components/index.js 1:14-32

Using "can-I-haz-build" has fixed it.

Thanks

**Comment by derekstavis** [comment]
Hey @myappincome, thanks for your testing! 🎉 

We just merged and pushed to NPM version 1.0.0.

Thank you again for testing! Be sure to revert your `package.json` back to NPM version!

Thanks @felquis and @MarcoWorms for the reviews! 💯
