### ISSUE TITLE
Please make a new release

### ISSUE THREAD

**Issue by singingwolfboy** [pagarme/react-event-components#46]
It looks like the [existing release on NPM](https://www.npmjs.com/package/react-event-components) (v1.0.0) still references `React.PropTypes`. The code in this repository does not. Can you make a new release on NPM, so that we can upgrade and avoid the deprecation warnings?

**Comment by MarcoWorms** [comment]
Sure we can! @derekstavis would you mind hitting that release button?

**Comment by derekstavis** [comment]
Done! Just uploaded 1.1.0 to NPM.

Sorry for the delay @singingwolfboy, and thanks for all the help!
