### ISSUE TITLE
Update dev dependencies

### ISSUE THREAD

**Issue by rodrigooler** [pagarme/react-event-components#50]
<img width="1286" alt="screen shot 2017-10-12 at 18 40 28" src="https://user-images.githubusercontent.com/5496931/31520668-fea03840-af7c-11e7-9314-d5facf5369b1.png">

**Comment by felquis** [comment]
Could send a PR?

**Comment by rodrigooler** [comment]
@felquis https://github.com/pagarme/react-event-components/pull/51
